// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using docker_compose_api_mssql;

namespace docker_compose_api_mssql.Migrations
{
    [DbContext(typeof(CoreContext))]
    partial class CoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("docker_compose_api_mssql.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "6f2f1cae-af15-40ec-99fe-630cec26628e",
                            Title = "本教程由Siegrain傾情奉獻?️"
                        },
                        new
                        {
                            Id = 2,
                            Content = "f4f7ae03-7825-459c-93d5-a4b038609833",
                            Title = "感謝大家關註~"
                        },
                        new
                        {
                            Id = 3,
                            Content = "2e12945e-12c0-40be-8ff1-5542007c885a",
                            Title = "博客地址為 http://siegrain.wang"
                        },
                        new
                        {
                            Id = 4,
                            Content = "d3a9b305-00a4-4f9b-b1cc-428b379e9180",
                            Title = "本教程Github地址為 https://github.com/Seanwong933/.NET-Core-with-Docker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
